### ISSUE TITLE
Functions for Integer sign and unsign are missing

### ISSUE THREAD

**Issue by ptprasanna** [riscv-software-src/riscv-isac#62]
https://github.com/riscv-software-src/riscv-isac/blob/9dc9503c9cce79d8c93d8f4955111f2f6d1ad9c7/riscv_isac/InstructionObject.py#L285

For rs3 the functions has to be defined with respect to sign and unsigned values.

**Comment by pawks** [comment]
There aren't any 3 operand integer instructions currently. Closing this as it is irrelevant with the current state of support.
